application:
  name: BigCore Logistics Pipeline

spark:
  master: local[*]

paths:
  drivers: data/motoristas
  travels: data/viagens
  vehicles: data/veiculos
  tracking: data/rastreamento
  geofences: data/geocercas

output:
  raw: output/raw 
  
  trusted:
    vehicles: output/trusted/vehicles
    drivers: output/trusted/drivers
    travels: output/trusted/travels
    tracking: output/trusted/tracking
  
  analytics:
    trip_summary: output/analytics/trip_summary

quality:

  vehicles:
    required_columns:
      - veiculo_id
      - placa
      - status

    required_values:
      - veiculo_id
      - placa
      - status
      
    primary_key:
      - veiculo_id
      
    null_values:
      placa: "NOT_INFORMED"
      marca: "NOT_INFORMED"
      modelo: "NOT_INFORMED"
      ano_fabricacao: 0
      tipo: "NOT_INFORMED"
      capacidade_kg: 0    
      capacidade_paletes: 0
      km_atual: 0
      status: "UNKNOWN"

  drivers:
    required_columns:
      - motorista_id
      - nome

    required_values:
      - motorista_id
      - nome
      
    primary_key:
      - motorista_id

    null_values:
      nome: "NOT_INFORMED"
      cpf: "NOT_INFORMED"
      cnh: "NOT_INFORMED"
      categoria_cnh: "NOT_INFORMED"
      telefone: "NOT_INFORMED"
      base_operacional: "NOT_INFORMED"
      status: "UNKNOWN"

  travels:
    required_columns:
      - viagem_id
      - motorista_id
      - veiculo_id

    required_values:
      - viagem_id
      - motorista_id
      - veiculo_id

    primary_key:
      - viagem_id

    null_values:
      status: "UNKNOWN"
      distancia_km: 0
      peso_carga_kg: 0
      
  tracking:
    required_columns:
      - posicao_id
      - veiculo_id
      - timestamp
      - latitude
      - longitude
      
    required_values:
      - posicao_id
      - veiculo_id
      - timestamp
      - latitude
      - longitude
      
    primary_key:
      - posicao_id