application:
  name: BigCore Logistics Pipeline

spark:
  master: local[*]

paths:
  drivers: data/motoristas
  travels: data/viagens
  vehicles: data/veiculos
  tracking: data/rastreamento
  geofences: data/geocercas

output:
  raw: output/raw
  trusted: output/trusted
  analytics: output/analytics

quality:

  vehicles:
    required_columns:
      - veiculo_id
      - placa
      - status

    required_values:
      - veiculo_id
      - placa
      - status
      
    primary_key:
      - veiculo_id      

  drivers:
    required_columns:
      - motorista_id
      - nome

    required_values:
      - motorista_id
      - nome
      
    primary_key:
      - motorista_id      

  travels:
    required_columns:
      - viagem_id
      - motorista_id
      - veiculo_id

    required_values:
      - viagem_id
      - motorista_id
      - veiculo_id

    primary_key:
      - viagem_id

  tracking:
    required_columns:
      - posicao_id
      - veiculo_id
      - timestamp
      - latitude
      - longitude
      
    required_values:
      - posicao_id
      - veiculo_id
      - timestamp
      - latitude
      - longitude
      
    primary_key:
      - posicao_id